---
### train para ####
name: 'voc'
isDetailLog : 0
max_iter: 120000
lr_steps: [80000, 100000, 120000]
batch_size: 1
num_workers: 0                                          # Number of workers used in dataloading, 0 means only the main thread is used in data loading
initial_lr: 0.0001
momentum: 0.9
weight_decay: 0.0005
gamma: 0.1
PREPROCESS_MEAN : [104.0, 117.0, 123.0]

### network architecture ####
num_classes: 21      
basenet_checkpt_path: "./weights/vgg16_reducedfc.pth"
feature_maps: [38, 19, 10, 5, 3, 1]                     # size of each feature map  (can be changed?)
min_dim: 300                                            # input image size (can be changed?)
steps: [8, 16, 32, 64, 100, 300]                        # meaning? (can be changed?)
min_sizes: [30, 60, 111, 162, 213, 264]
max_sizes: [60, 111, 162, 213, 264, 315]                 # it control prior box sizes (can be changed?)
aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]  # it control prior box aspect ratio (can be changed?)
variance: [0.1, 0.2]                                    # it does sth in the prior box (can be changed?)
clip: True                                              # it does sth in the prior box (can be changed?)

...
